indprod = rio::import("ind_baza-2018.xsls", skip = 2, sheet = 1)
indprod_vector = t(indprod[2, 3:ncol(indprod)])
# for periods before January, 2020 use old link for the data and start = c(2015, 1)
indprod_ts = stats::ts(indprod_vector, start = c(2013, 1), frequency = 12)
indprod_tsibble = tsibble::as_tsibble(indprod_ts)
indprod_tsibble = dplyr::rename(indprod_tsibble, date = index, ind_prod = value)
indprod_tsibble = dplyr::mutate(indprod_tsibble, access_date = access_date)